name: LiquidStarval
version: '${project.version}'
main: de.starvalcity.base.Core
api-version: 1.16
authors: [ StarvalCity ]
description: StarvalCity API Reference
commands:
  attachinfo:
    description: Checks if a player is attached
    usage: /attachinfo [Playername]