name: LiquidStarval
version: '${project.version}'
main: de.starvalcity.base.Core
api-version: 1.16
authors: [ StarvalCity ]
description: StarvalCity API

commands:
  attach:
    description: Attach Command
    usage: /attach
  economy:
    description: Economy Command
    usage: /economy
    aliases:
      - eco
      - wirtschaft